### ISSUE TITLE
The Portfolio background issue

### ISSUE THREAD

**Issue by AbednegoKibitok** [joyapisi/ThePortfolio#3]
- [x] I think it would be better if you used the box-sizing property to avoid spaces at the end and the beginning of your screen.
- [x] I think putting the solid color before the background image would be better to avoid the background image being hidden.

**Comment by mahabubx7** [comment]
> * [ ]  I think it would be better if you used the box-sizing property to avoid spaces at the end and the beginning of your screen.
> * [ ]  I think putting the solid color before the background image would be better to avoid the background image being hidden.

:rocket: let's do this

**Comment by joyapisi** [comment]
> * [x]  I think it would be better if you used the box-sizing property to avoid spaces at the end and the beginning of your screen.
> * [x]  I think putting the solid color before the background image would be better to avoid the background image being hidden.

Thank you. I have implemented the changes.
