### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Hazard10-eng** [joyapisi/ThePortfolio#9]
- Great job for implementing changes. However your code is missing the navbar. please stick to the figma template
- Also Increase the font of the first header, make sure it looks like from your using template.

ciao 😄

**Comment by joyapisi** [comment]
> * Great job for implementing changes. However your code is missing the navbar. please stick to the figma template
> * Also Increase the font of the first header, make sure it looks like from your using template.
> 
> ciao 😄

Thank you. I will implement these changes.
